In [38]:
import pandas as pd

#pip install scikit-learn

In [39]:
# Célula 2 — Carregamento do dataset

# Opção 1: CSV
df = pd.read_csv("br_seeg_emissoes_brasil.csv")

# Visualizar primeiras linhas
df.head()

,ano,nivel_1,nivel_2,nivel_3,nivel_4,nivel_5,nivel_6,tipo_emissao,gas,atividade_economica,produto,emissao
0,1970,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,230462.17
1,1971,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,226016.30
2,1972,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,220101.20
3,1973,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,214195.56
4,1974,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,186862.84

In [40]:
# Célula 3 — Seleção das colunas relevantes

df = df[["ano", "nivel_1", "gas", "emissao"]]

df.head()

    ano       nivel_1      gas    emissao
0  1970  Agropecuária  CH4 (t)  230462.17
1  1971  Agropecuária  CH4 (t)  226016.30
2  1972  Agropecuária  CH4 (t)  220101.20
3  1973  Agropecuária  CH4 (t)  214195.56
4  1974  Agropecuária  CH4 (t)  186862.84

In [41]:
# Célula 4 — Filtrar apenas emissões de CO2

df_co2 = df[df["gas"] == "CO2 (t)"]

df_co2.head()
df_co2.count()

ano        37550
nivel_1    37550
gas        37550
emissao    30795
dtype: int64

In [42]:
# Célula 5 — Remoção de valores nulos

# df_co2 = df_co2.dropna()

# Verificar se ainda existem valores nulos
# df_co2.isnull().sum()
# df_co2.count()

# Achamos que não é necessário remover os valores nulos, pois eles representam anos ou atividades sem emissões de CO2, o que é relevante para a análise. Portanto, optamos por manter os valores nulos para preservar a integridade dos dados e evitar distorções na análise.

In [43]:
# Célula 6 — Aplicação de One-Hot Encoding

df_encoded = pd.get_dummies(
    # get_dummies é uma função do pandas que converte variáveis categóricas em variáveis dummy (0 ou 1)
    df_co2,
    columns=["nivel_1"],
    drop_first=True  # evita redundância
)

df_encoded.head()

,ano,gas,emissao,nivel_1_Energia,nivel_1_Mudança de Uso da Terra e Floresta,nivel_1_Processos Industriais,nivel_1_Resíduos
14150,1970,CO2 (t),223538.51,False,False,False,False
14151,1971,CO2 (t),225473.06,False,False,False,False
14152,1972,CO2 (t),333445.33,False,False,False,False
14153,1973,CO2 (t),280380.69,False,False,False,False
14154,1974,CO2 (t),315281.04,False,False,False,False

In [44]:
# Célula 7 — Normalização da variável de resposta (Emissão)

df_encoded["Emissao_norm"] = (
    df_encoded["emissao"] - df_encoded["emissao"].min()
) / (
    df_encoded["emissao"].max()
    - df_encoded["emissao"].min()
)

df_encoded.head()

,ano,gas,emissao,nivel_1_Energia,nivel_1_Mudança de Uso da Terra e Floresta,nivel_1_Processos Industriais,nivel_1_Resíduos,Emissao_norm
14150,1970,CO2 (t),223538.51,False,False,False,False,0.129892
14151,1971,CO2 (t),225473.06,False,False,False,False,0.129893
14152,1972,CO2 (t),333445.33,False,False,False,False,0.129938
14153,1973,CO2 (t),280380.69,False,False,False,False,0.129916
14154,1974,CO2 (t),315281.04,False,False,False,False,0.129931

In [45]:
# Célula 8 — Remover valores nulos (NaN)

df_encoded = df_encoded.dropna()

print(f"Dados após remover NaN: {len(df_encoded)} linhas")
df_encoded.head()

Dados após remover NaN: 30795 linhas

,ano,gas,emissao,nivel_1_Energia,nivel_1_Mudança de Uso da Terra e Floresta,nivel_1_Processos Industriais,nivel_1_Resíduos,Emissao_norm
14150,1970,CO2 (t),223538.51,False,False,False,False,0.129892
14151,1971,CO2 (t),225473.06,False,False,False,False,0.129893
14152,1972,CO2 (t),333445.33,False,False,False,False,0.129938
14153,1973,CO2 (t),280380.69,False,False,False,False,0.129916
14154,1974,CO2 (t),315281.04,False,False,False,False,0.129931

# Modelos de Regressão.

Regressão Linear Multipla.  Multiple Linear Regression (MLR)

In [46]:
X = df_encoded.drop(['emissao', 'gas'], axis=1)  # variáveis independentes (removendo a coluna alvo e 'gas' que é redundante)
y = df_encoded['emissao']               # variável alvo

In [47]:
# Célula 9 — Divisão dos dados

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
        # test_size=0.2 significa que 20% dos dados serão usados para teste e 80% para treino.
        # random_state=42 é uma semente para garantir que a divisão seja a mesma toda vez que o código for executado, permitindo reprodutibilidade.
)

In [48]:
# Célula 10 — Treinamento da Regressão Linear Múltipla

from sklearn.linear_model import LinearRegression

modelo_linear = LinearRegression()
modelo_linear.fit(X_train, y_train)

LinearRegression()

In [49]:
# Célula 11 — Treinamento da Regressão Árvore de Decisão
from sklearn.tree import DecisionTreeRegressor 

modelo_arvore = DecisionTreeRegressor(max_depth=5)
modelo_arvore.fit(X_train, y_train)

# ANOTAÇOES:
# * A arevore de decisão com certeza é melhor que a arevore de regração linar 
# * pode ser que deva ser aplicado overfitting (overfitting é um modelo que decora os dados de treinamento) na arvore de decição, devemos avaliar a arvore antes de implementar ele pois quando chega um dado novo ele pode dar problemas de desempenho.

# se quiser visualizar a arvore de decisão é so aplicar

# from sklearn.tree import plot_tree
# import matplotlib.pyplot as plt

# plt.figure(figsize=(12,8))
# plot_tree(modelo, filled=True)
# plt.show()
#

DecisionTreeRegressor(max_depth=5)

In [50]:
# Célula 12 — Treinamento da Regressão Random Forest
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
modelo_floresta = RandomForestRegressor(max_depth=5)        # controla overfitting 

modelo_floresta.fit(X_train, y_train)

RandomForestRegressor(max_depth=5)

In [51]:
# Célula 13 — Treinamento da Regressão XGBoost
import xgboost as xgb 
from sklearn.metrics import mean_squared_error

modelo_xgb = xgb.XGBRegressor(max_depth=5)  # max_depth controla overfitting, n_estimators é o número de árvores, learning_rate é a taxa de aprendizado
modelo_xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [52]:
from sklearn.metrics import mean_squared_error
import numpy as np

# Previsões
y_pred_linear = modelo_linear.predict(X_test)
y_pred_arvore = modelo_arvore.predict(X_test)
y_pred_floresta = modelo_floresta.predict(X_test)
y_pred_xgb = modelo_xgb.predict(X_test)

print("===== TAXA DE ERRO (RMSE) =====\n")

print("Regressão Linear:", np.sqrt(mean_squared_error(y_test, y_pred_linear)))
print("Árvore de Decisão:", np.sqrt(mean_squared_error(y_test, y_pred_arvore)))
print("Floresta:", np.sqrt(mean_squared_error(y_test, y_pred_floresta)))
print("XGBoost:", np.sqrt(mean_squared_error(y_test, y_pred_xgb)))

===== TAXA DE ERRO (RMSE) =====

Regressão Linear: 2.6168697274892995e-07
Árvore de Decisão: 3860403.255519237
Floresta: 3191874.918977059
XGBoost: 27240323.195821017