In [5]:
import pandas as pd

In [6]:
# Célula 2 — Carregamento do dataset

# Opção 1: CSV
df = pd.read_csv("br_seeg_emissoes_brasil.csv")

# Visualizar primeiras linhas
df.head()

,ano,nivel_1,nivel_2,nivel_3,nivel_4,nivel_5,nivel_6,tipo_emissao,gas,atividade_economica,produto,emissao
0,1970,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,230462.17
1,1971,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,226016.30
2,1972,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,220101.20
3,1973,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,214195.56
4,1974,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,186862.84

In [7]:
# Célula 3 — Seleção das colunas relevantes

df = df[["ano", "nivel_1", "gas", "emissao"]]

df.head()

    ano       nivel_1      gas    emissao
0  1970  Agropecuária  CH4 (t)  230462.17
1  1971  Agropecuária  CH4 (t)  226016.30
2  1972  Agropecuária  CH4 (t)  220101.20
3  1973  Agropecuária  CH4 (t)  214195.56
4  1974  Agropecuária  CH4 (t)  186862.84